### ISSUE TITLE
Nametags no longer work

### ISSUE THREAD

**Issue by HBIDamian** [poggit-orphanage/PureChat#17]
No matter how many times I try, I am unable to get nametags to work. 
This could be due to one of the Minecraft updates. 

![image](https://user-images.githubusercontent.com/10010369/46414330-d156bd80-c71a-11e8-9279-3348b8bad874.png)
![image](https://user-images.githubusercontent.com/10010369/46414456-0e22b480-c71b-11e8-9dc1-2ead8c46c07a.png)

**Comment by TheDeibo** [comment]
Update: 
With @Muqsit 's `BedrockFix` plugin, I have got it to work. 
It should be added directly to PureChat

**Comment by Muqsit** [comment]
Yeah, mojang broke it in 1.6 and fixed it in 1.7 (beta). *Hopefully* it remains fixed in 1.7's release.

**Comment by kevinishawesome** [comment]
@TheDeibo  Please close the issue if problem is fixed
