### ISSUE TITLE
Suggetion add rankup

### ISSUE THREAD

**Issue by mikeygio10** [poggit-orphanage/PureChat#22]
add rankup so it show what rank you are with rankup like a to z or what ever

**Comment by provsnoobgaming** [comment]
There is a seperate repository that you can use for ranking up please use that

**Comment by provsnoobgaming** [comment]
it can be found here https://poggit.pmmp.io/ci/provsnoobgaming/RankUp/RankUp

**Comment by mikeygio10** [comment]
The repo provsnoobgaming/RankUp does not exist or is not accessible to your GitHub account (@mikeygio10).

**Comment by provsnoobgaming** [comment]
try this instead
https://github.com/AloofXFireYT/RankUp

**Comment by mikeygio10** [comment]
but then how do i set it up with purechat

**Comment by provsnoobgaming** [comment]
make it so rankup uses pureperms
and add A-Z groups using pureperms
and use /setprefix A null §a[A] §b{display_name} {msg}
PLEASE MAKE AN EFFORT TO READ README.MD

**Comment by mikeygio10** [comment]
o sorry did not see it
lol

**Comment by provsnoobgaming** [comment]
you can go back to leet tbh

**Comment by TurTiMo** [comment]
is it possible to have a rank (of RankUp) **and** a grade (founder, admin, player, ...) ? if yes, how ?
