### ISSUE TITLE
Unable to set a players suffix/prefix via console

### ISSUE THREAD

**Issue by CtrlAltTr0ll** [poggit-orphanage/PureChat#31]
why is the console not allowed to set players prefix/suffix? is there a way to backdoor this with another plugin?

without the ability to do so it makes it impossible for people to use buycraft to set a customers suffix (for example) to [VIP]

**Comment by jaylac2000** [comment]
Check out TitleADR

**Comment by ItsMax123** [comment]
TitleADR doesnt exist
