### ISSUE TITLE
Internal server error when trying to log in

### ISSUE THREAD

**Issue by TNT10128** [poggit-orphanage/PureChat#33]
When I use the plugin with PurePerms, the server refuses to let me in and says "Internal server error." I've tried reinstalling, nothing worked. It worked without PurePerms, though. Is this a bug or does it have to do with my Pocketmine version?

**Comment by jaylac2000** [comment]
you must have an error. can you post the error as well as your config. post your config here https://pastebin.com/

**Comment by TNT10128** [comment]
[Console output from my server & config files for Purechat/Pureperms](https://pastebin.com/ZwZiTSfc)

**Comment by jaylac2000** [comment]
it looks like an error with your perms file can you post your pure perms there

you probably have extra spaces where they shouldnt be

**Comment by TNT10128** [comment]
https://pastebin.com/hjuVRske - groups file, if that's what you're looking for

**Comment by jaylac2000** [comment]
your error is Moderator **pocketmine.command.kick** you are missing the -

**Comment by jaylac2000** [comment]
actually, theres more... just delete your config and re do it

**Comment by TNT10128** [comment]
Thank you, I will fix the config and let you know how everything worked out when I have access to my computer again.

**Comment by TNT10128** [comment]
Worked, I am no longer kicked when the plugins are installed.
Resolved, closed.
