### ISSUE TITLE
/setsuffix and /setprefix

### ISSUE THREAD

**Issue by TheShinPin** [poggit-orphanage/PureChat#6]
You cant set another players suffix/prefix.

When you try and do this it just combines the name and the prefix/suffix

It would be nice if this was fixed, as it would allow people to say buy tags without being able to change them to whatever they want. Plus I'm pretty sure this is how it is supposed to be, judging from your read me page. Thanks.

**Comment by Awzaw** [comment]
This was never possible, and I don't see why you'd want to allow it: the usage is: /setprefix <prefix>
